# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experience', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('first_name', models.CharField(default=b'', max_length=30, verbose_name=b'first name')),
                ('last_name', models.CharField(default=b'', max_length=30)),
                ('number', models.CharField(default=b'', max_length=15)),
                ('email', models.EmailField(default=b'', max_length=75)),
                ('reason', models.TextField(default=b'')),
                ('order_id', models.CharField(default=b'', editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('order_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience.Experience', verbose_name=b'Experience')),
            ],
        ),
    ]
