# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('name', models.CharField(default=b'', max_length=50)),
                ('location', models.CharField(default=b'', max_length=50)),
                ('number', models.CharField(default=b'', max_length=15)),
                ('email', models.EmailField(default=b'', max_length=75)),
                ('description', models.TextField(default=b'')),
                ('photo', models.CharField(default=b'', max_length=250)),
                ('experience_id', models.CharField(default=b'', editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('creation_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
